### ISSUE TITLE
取经

### ISSUE THREAD

**Issue by webproblem** [sophiayang1997/notebook#2]
来取经了，很优秀，学习如何写博客，顺便退下我的笔记，https://github.com/webproblem/Blog/tree/master/%E5%89%8D%E7%AB%AF，可以多多交流。

**Comment by sophiayang1997** [comment]
谢谢~目前该仓库文章也没有完全规范化，希望有错误能多提多指正~

**Comment by webproblem** [comment]
可以的，可以多交流技术，follow你了
